src/Entity/Currency.php
<?php

namespace App\Entity;

use Ramsey\Uuid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CurrencyRepository;
use Ramsey\Uuid\Doctrine\UuidGenerator;

#[ORM\Entity(repositoryClass: CurrencyRepository::class)]
class Currency
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: "CUSTOM")]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, unique: true)]
    private $currency_code;

    #[ORM\Column(type: 'float')]
    private $exchange_rate;

    public function __construct($name, $currency_code, $exchange_rate)
    {
        $this->id = Uuid::uuid4();
        $this->name = $name;
        $this->currency_code = $currency_code;
        $this->exchange_rate = $exchange_rate;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCurrencyCode(): ?string
    {
        return $this->currency_code;
    }

    public function setCurrencyCode(string $currency_code): self
    {
        $this->currency_code = $currency_code;

        return $this;
    }

    public function getExchangeRate(): ?float
    {
        return $this->exchange_rate;
    }

    public function setExchangeRate(float $exchange_rate): self
    {
        $this->exchange_rate = $exchange_rate;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\CurrencyRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(CurrencyRepository $currencyRepo): Response
    {
        return $this->render('home/index.html.twig', [
            'title' => 'Currency Exchange Rates',
            'rates' => $currencyRepo->findAll()
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
<style>
    .wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="wrapper">
{% if rates|length > 0 %}
    Current exchange rates in database:
    <ul>
    {% for rate in rates %}
        <li>{{ rate.name }} - <code>{{ rate.currencyCode }}</code> - {{ rate.exchangeRate }} PLN</li>
    {% endfor %}
    </ul>
{% else %}
    No exchange rates present in database!<br><br>
    If you're the admin, please run command: <br>
    <code>symfony console app:update-exchange-rates</code>
{% endif %}
</div>
{% endblock %}